from .extensions import db
from sqlalchemy.dialects.mysql import LONGTEXT

class MovType(db.Model):
    __tablename__ = 'sakura_movtype'
    type_id = db.Column(db.Integer, primary_key=True)
    type_name = db.Column(db.String(20), nullable=False)
    this_type_movies = db.relationship('MovInfo', back_populates='this_mov_type')
    this_type_movie_details = db.relationship('MovDetail', back_populates='this_mov_type')


class MovInfo(db.Model):
    __tablename__ = 'sakura_movinfo'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    type_id = db.Column(db.Integer, db.ForeignKey('sakura_movtype.type_id'))  # 一对多关系,ForeignKey在多侧
    type_name = db.Column(db.String(20), nullable=False)
    vod_en = db.Column(db.Text, nullable=False)
    vod_id = db.Column(db.Integer, primary_key=True)
    vod_name = db.Column(db.Text, nullable=False)
    vod_play_from = db.Column(db.Text)
    vod_remarks = db.Column(db.Text)
    vod_time = db.Column(db.DateTime)
    this_mov_type = db.relationship('MovType', back_populates='this_type_movies')


class MovDetail(db.Model):
    __tablename__ = 'sakura_movdetail'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    group_id = db.Column(db.Integer)
    type_id = db.Column(db.Integer, db.ForeignKey('sakura_movtype.type_id'))  # 一对多,设置外键
    type_id_1 = db.Column(db.Integer)
    type_name = db.Column(db.String(20))
    vod_actor = db.Column(db.Text)
    vod_area = db.Column(db.Text)
    vod_author = db.Column(db.Text)
    vod_behind = db.Column(db.Text)
    vod_blurb = db.Column(db.Text)
    vod_class = db.Column(db.Text)
    vod_color = db.Column(db.Text)
    vod_content = db.Column(db.Text)
    vod_copyright = db.Column(db.Integer)
    vod_director = db.Column(db.Text)
    vod_douban_id = db.Column(db.Integer)
    vod_douban_score = db.Column(db.String(20))
    vod_down = db.Column(db.Integer)
    vod_down_from = db.Column(db.Text)
    vod_down_note = db.Column(db.Text)
    vod_down_server = db.Column(db.Text)
    vod_down_url = db.Column(db.Text)
    vod_duration = db.Column(db.Text)
    vod_en = db.Column(db.Text)
    vod_hits = db.Column(db.Integer)
    vod_hits_day = db.Column(db.Integer)
    vod_hits_month = db.Column(db.Integer)
    vod_hits_week = db.Column(db.Integer)
    vod_id = db.Column(db.Integer, primary_key=True)
    vod_isend = db.Column(db.Integer)
    vod_jumpurl = db.Column(db.Text)
    vod_lang = db.Column(db.Text)
    vod_letter = db.Column(db.Text)
    vod_level = db.Column(db.Integer)
    vod_lock = db.Column(db.Integer)
    vod_name = db.Column(db.Text)
    vod_pic = db.Column(db.Text)
    vod_pic_screenshot = db.Column(db.Text)
    vod_pic_slide = db.Column(db.Text)
    vod_pic_thumb = db.Column(db.Text)
    vod_play_from = db.Column(db.Text)
    vod_play_note = db.Column(db.Text)
    vod_play_server = db.Column(db.Text)
    vod_play_url = db.Column(LONGTEXT)
    vod_plot = db.Column(db.Integer)
    vod_plot_detail = db.Column(db.Text)
    vod_plot_name = db.Column(db.Text)
    vod_points = db.Column(db.Integer)
    vod_points_down = db.Column(db.Integer)
    vod_points_play = db.Column(db.Integer)
    vod_pubdate = db.Column(db.Text)
    vod_pwd = db.Column(db.Text)
    vod_pwd_down = db.Column(db.Text)
    vod_pwd_down_url = db.Column(db.Text)
    vod_pwd_play = db.Column(db.Text)
    vod_pwd_play_url = db.Column(db.Text)
    vod_pwd_url = db.Column(db.Text)
    vod_rel_art = db.Column(db.Text)
    vod_rel_vod = db.Column(db.Text)
    vod_remarks = db.Column(db.Text)
    vod_reurl = db.Column(db.Text)
    vod_score = db.Column(db.Text)
    vod_score_all = db.Column(db.Integer)
    vod_score_num = db.Column(db.Integer)
    vod_serial = db.Column(db.Text)
    vod_state = db.Column(db.Text)
    vod_status = db.Column(db.Integer)
    vod_sub = db.Column(db.Text)
    vod_tag = db.Column(db.Text)
    vod_time = db.Column(db.DateTime)
    vod_time_add = db.Column(db.Integer)
    vod_time_hits = db.Column(db.Integer)
    vod_time_make = db.Column(db.Integer)
    vod_total = db.Column(db.Integer)
    vod_tpl = db.Column(db.Text)
    vod_tpl_down = db.Column(db.Text)
    vod_tpl_play = db.Column(db.Text)
    vod_trysee = db.Column(db.Integer)
    vod_tv = db.Column(db.Text)
    vod_up = db.Column(db.Integer)
    vod_version = db.Column(db.Text)
    vod_weekday = db.Column(db.Text)
    vod_writer = db.Column(db.Text)
    vod_year = db.Column(db.Text)
    this_mov_type = db.relationship('MovType', back_populates='this_type_movie_details')

